spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop


      package ru.myproject;

      import org.springframework.boot.SpringApplication;
      import org.springframework.boot.autoconfigure.SpringBootApplication;

      @SpringBootApplication
      public class ReservationImplApplication {
      
      public static void main(String[] args) {
      SpringApplication.run(ReservationImplApplication.class, args);
    }

  }
